# Generated by Django 2.2 on 2021-05-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
        migrations.CreateModel(
            name='UserRegistrationConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('hash', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на подтверждение регистрации',
                'verbose_name_plural': 'Запросы на подтверждение регистрации',
            },
        ),
    ]
