# Generated by Django 2.2 on 2021-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210522_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationconfirm',
            name='hash',
        ),
    ]
