# Generated by Django 2.2 on 2021-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userregistrationconfirm_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationconfirm',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
