# Generated by Django 2.2 on 2021-05-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_achievement_logo'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ для оплаты',
                'verbose_name_plural': 'Заказы для оплаты',
            },
        ),
    ]
