# Generated by Django 2.2 on 2021-05-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagemanager', '0001_initial'),
        ('catalog', '0004_auto_20210522_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagemanager.BaseImage', verbose_name='Лого'),
        ),
    ]
